<?php

$dictionary['asol_Project'] = array(
	'table'=>'asol_project',
	'audited'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (

  'date_start' => 
  array (
    'required' => false,
    'name' => 'date_start',
    'vname' => 'LBL_DATE_START',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'date_end' => 
  array (
    'required' => false,
    'name' => 'date_end',
    'vname' => 'LBL_DATE_END',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'status' => 
  array (
    'required' => false,
    'name' => 'status',
    'vname' => 'LBL_STATUS',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'draft',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'asol_project_status_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'priority' => 
  array (
    'required' => false,
    'name' => 'priority',
    'vname' => 'LBL_PRIORITY',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '1',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'asol_project_priority_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'log' => 
  array (
    'required' => false,
    'name' => 'log',
    'vname' => 'LBL_LOG',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'studio' => 'visible',
    'rows' => '6',
    'cols' => '200',
  ),
  'wiki_link' => 
  array (
    'required' => false,
    'name' => 'wiki_link',
    'vname' => 'LBL_WIKI_LINK',
    'type' => 'url',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
    'gen' => '',
    'link_target' => '_self',
  ),
  'wiki_link_alias' => 
  array (
    'required' => false,
    'name' => 'wiki_link_alias',
    'vname' => 'LBL_WIKI_LINK_ALIAS',
    'type' => 'url',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
    'gen' => '',
    'link_target' => '_self',
  ),
  'asol_projectversion_id_c' => 
  array (
    'required' => false,
    'name' => 'asol_projectversion_id_c',
    'vname' => 'LBL_WORKING_VERSION_ASOL_PROJECTVERSION_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'working_version' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'working_version',
    'vname' => 'LBL_WORKING_VERSION',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'asol_projectversion_id_c',
    'ext2' => 'asol_ProjectVersion',
    'module' => 'asol_ProjectVersion',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'asol_projectversion_id1_c' => 
  array (
    'required' => false,
    'name' => 'asol_projectversion_id1_c',
    'vname' => 'LBL_LAST_PUBLISHED_VERSION_ASOL_PROJECTVERSION_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'last_published_version' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'last_published_version',
    'vname' => 'LBL_LAST_PUBLISHED_VERSION',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'asol_projectversion_id1_c',
    'ext2' => 'asol_ProjectVersion',
    'module' => 'asol_ProjectVersion',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  
  'jquery_gantt' =>
  array (
      'name' => 'jquery_gantt',
      'type' => 'varchar',
      'source'=>'non-db',
      'vname'=>'LBL_JQUERY_GANTT',
  ),
  
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('asol_Project','asol_Project', array('basic','assignable'));