<?php

$dictionary['asol_ProjectVersion'] = array(
'table'=>'asol_projectversion',
'audited'=>true,
'duplicate_merge'=>true,

'fields'=>array (
  
	'version' . '_number' => 
	array (
		'name' => 'version' . '_number',
		'vname' => 'LBL_VERSION_NUMBER',
		'type' => 'int',
		'readonly' => true,
		'len' => 11,
		'required' => true,
		//'auto_increment' => true,
		'unified_search' => true,
		'full_text_search' => array('boost' => 3),
		'comment' => 'Visual unique identifier',
		'duplicate_merge' => 'disabled',
		'disable_num_format' => true,
		'studio' => array('quickcreate' => false),
	),

  'json_gantt_tasks' => 
  array (
    'required' => false,
    'name' => 'json_gantt_tasks',
    'vname' => 'LBL_JSON_GANTT_TASKS',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  	'dbType' => 'mediumtext',
  ),
  'is_published' => 
  array (
    'required' => false,
    'name' => 'is_published',
    'vname' => 'LBL_IS_PUBLISHED',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'published_datetime' => 
  array (
    'required' => false,
    'name' => 'published_datetime',
    'vname' => 'LBL_PUBLISHED_DATETIME',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
    'dbType' => 'datetime',
  ),
  'user_id_c' => 
  array (
    'required' => false,
    'name' => 'user_id_c',
    'vname' => 'LBL_CURRENT_EDITOR_USER_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'current_editor' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'current_editor',
    'vname' => 'LBL_CURRENT_EDITOR',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'user_id_c',
    'ext2' => 'Users',
    'module' => 'Users',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'last_editor_call' => 
  array (
    'required' => false,
    'name' => 'last_editor_call',
    'vname' => 'LBL_LAST_EDITOR_CALL',
    'type' => 'datetimecombo',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
    'dbType' => 'datetime',
  ),
  'wiki_link' => 
  array (
    'required' => false,
    'name' => 'wiki_link',
    'vname' => 'LBL_WIKI_LINK',
    'type' => 'url',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
    'gen' => '',
    'link_target' => '_self',
  ),
  'wiki_link_alias' => 
  array (
    'required' => false,
    'name' => 'wiki_link_alias',
    'vname' => 'LBL_WIKI_LINK_ALIAS',
    'type' => 'url',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
    'gen' => '',
    'link_target' => '_self',
  ),
  'log' => 
  array (
    'required' => false,
    'name' => 'log',
    'vname' => 'LBL_LOG',
    'type' => 'text',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'studio' => 'visible',
    'rows' => '6',
    'cols' => '200',
  ),
  'type' => 
  array (
    'required' => false,
    'name' => 'type',
    'vname' => 'LBL_TYPE',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'start',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'asol_projectversion_type_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'jquery_gantt' =>
  array (
      'name' => 'jquery_gantt',
      'type' => 'varchar',
      'source'=>'non-db',
      'vname'=>'LBL_JQUERY_GANTT',
  ),
),

/*
'indices'=>array(
	 'number'=>array('name' =>'version' . 'numk', 'type' =>'unique', 'fields'=>array('version' . '_number'))
),
*/

	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('asol_ProjectVersion','asol_ProjectVersion', array('basic','assignable'));