<?php

$dictionary['asol_ProjectTask'] = array(
	'table'=>'asol_projecttask',
	'audited'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (
/*
  'start' => 
  array (
    'required' => false,
    'name' => 'start',
    'vname' => 'LBL_START',
    'type' => 'int',
  	'dbType' => 'long',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '50',
    'enable_range_search' => false,
    'disable_num_format' => '',
  ),
  'end' => 
  array (
    'required' => false,
    'name' => 'end',
    'vname' => 'LBL_END',
    'type' => 'int',
  	'dbType' => 'long',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '50',
    'enable_range_search' => false,
    'disable_num_format' => '',
  ),
*/
  'start' => 
  array (
    'required' => false,
    'name' => 'start',
    'vname' => 'LBL_START',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'end' => 
  array (
    'required' => false,
    'name' => 'end',
    'vname' => 'LBL_END',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),

  'status' => 
  array (
    'required' => false,
    'name' => 'status',
    'vname' => 'LBL_STATUS',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'draft',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'asol_projecttask_status_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'start_is_milestone' => 
  array (
    'required' => false,
    'name' => 'start_is_milestone',
    'vname' => 'LBL_START_IS_MILESTONE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'end_is_milestone' => 
  array (
    'required' => false,
    'name' => 'end_is_milestone',
    'vname' => 'LBL_END_IS_MILESTONE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
  ),
  'depends' => 
  array (
    'required' => false,
    'name' => 'depends',
    'vname' => 'LBL_DEPENDS',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'level' => 
  array (
    'required' => false,
    'name' => 'level',
    'vname' => 'LBL_LEVEL',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
  ),
  
  'duration' => 
  array (
    'required' => false,
    'name' => 'duration',
    'vname' => 'LBL_DURATION',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
  ),
  
  'progress' => 
  array (
    'required' => false,
    'name' => 'progress',
    'vname' => 'LBL_PROGRESS',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
  ),
  
  'task_order' => 
  array (
    'required' => false,
    'name' => 'task_order',
    'vname' => 'LBL_TASK_ORDER',
    'type' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
  ),
  
  'assigs' =>
  array(
  	'required' => false,
    'name' => 'assigs',
    'vname' => 'LBL_ASSIGS',
    'type' => 'text',
  ),
  
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('asol_ProjectTask','asol_ProjectTask', array('basic','assignable'));